/*
 * Copyright (c) Velocity BPA, LLC
 * Licensed under the Business Source License 1.1
 * Commercial use requires a separate commercial license.
 * See LICENSE file for details.
 */

/**
 * Healthcare Adjustment Codes
 * 
 * Claim Adjustment Reason Codes (CARC) and Remittance Advice Remark Codes (RARC)
 * Used in 835 ERA processing and claim adjudication
 */

/**
 * Claim Adjustment Group Codes
 * Categorizes the type of adjustment
 */
export const CLAIM_ADJUSTMENT_GROUPS = {
  CO: { code: 'CO', description: 'Contractual Obligations', responsibility: 'Provider' },
  CR: { code: 'CR', description: 'Corrections and Reversals', responsibility: 'Varies' },
  OA: { code: 'OA', description: 'Other Adjustments', responsibility: 'Varies' },
  PI: { code: 'PI', description: 'Payer Initiated Reductions', responsibility: 'Provider' },
  PR: { code: 'PR', description: 'Patient Responsibility', responsibility: 'Patient' },
} as const;

/**
 * Common Claim Adjustment Reason Codes (CARC)
 * These codes explain why a claim was adjusted from the billed amount
 */
export const CLAIM_ADJUSTMENT_REASON_CODES = {
  '1': 'Deductible Amount',
  '2': 'Coinsurance Amount',
  '3': 'Co-payment Amount',
  '4': 'The procedure code is inconsistent with the modifier used or a required modifier is missing',
  '5': 'The procedure code/bill type is inconsistent with the place of service',
  '6': 'The procedure/revenue code is inconsistent with the patient\'s age',
  '7': 'The procedure/revenue code is inconsistent with the patient\'s gender',
  '8': 'The procedure code is inconsistent with the provider type/specialty',
  '9': 'The diagnosis is inconsistent with the patient\'s age',
  '10': 'The diagnosis is inconsistent with the patient\'s gender',
  '11': 'The diagnosis is inconsistent with the procedure',
  '12': 'The diagnosis is inconsistent with the provider type',
  '13': 'The date of death precedes the date of service',
  '14': 'The date of birth follows the date of service',
  '15': 'The authorization number is missing, invalid, or does not apply',
  '16': 'Claim/service lacks information needed for adjudication',
  '17': 'Requested information was not provided or was insufficient/incomplete',
  '18': 'Exact duplicate claim/service',
  '19': 'This is a work-related injury/illness and thus the liability of the Worker\'s Compensation Carrier',
  '20': 'This injury/illness is covered by the liability carrier',
  '21': 'This injury/illness is the liability of the no-fault carrier',
  '22': 'This care may be covered by another payer per coordination of benefits',
  '23': 'The impact of prior payer(s) adjudication including payments and/or adjustments',
  '24': 'Charges are covered under a capitation agreement/managed care plan',
  '26': 'Expenses incurred prior to coverage',
  '27': 'Expenses incurred after coverage terminated',
  '29': 'The time limit for filing has expired',
  '31': 'Patient cannot be identified as our insured',
  '32': 'Our records indicate that this dependent is not an eligible dependent as defined',
  '33': 'Insured has no dependent coverage',
  '34': 'Insured has no coverage for newborns',
  '35': 'Lifetime benefit maximum has been reached',
  '38': 'Services not provided or authorized by designated provider',
  '39': 'Services denied at the time authorization was requested',
  '40': 'Charges do not meet qualifications for emergent/urgent care',
  '42': 'Charges exceed our fee schedule or maximum allowable amount',
  '45': 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement',
  '49': 'Routine/Preventive exam; this is not a covered benefit',
  '50': 'These are non-covered services because this is not deemed a medical necessity',
  '51': 'These are non-covered services because this is a pre-existing condition',
  '52': 'The referring/prescribing/rendering provider is not eligible to refer/prescribe/order/perform the service',
  '53': 'Services by an immediate relative or a member of the same household are not covered',
  '54': 'Multiple physicians/assistants are not covered in this case',
  '55': 'Procedure/treatment/drug is deemed experimental/investigational by the payer',
  '56': 'Procedure/treatment has not been deemed \'proven to be effective\' by the payer',
  '57': 'Payment denied/reduced for services not rendered or unbundled',
  '58': 'Treatment was deemed by the payer to have been rendered in an inappropriate/invalid setting',
  '59': 'Processed based on multiple or concurrent procedure rules',
  '60': 'Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services',
  '61': 'Adjustment due to the outpatient PPS/APC',
  '66': 'Blood Deductible',
  '69': 'Day outlier amount',
  '70': 'Cost outlier - Adjustment to Outlier Payment',
  '89': 'Professional fees removed from charges',
  '90': 'Ingredient cost adjustment',
  '91': 'Dispensing fee adjustment',
  '94': 'Plan procedures not followed',
  '95': 'Plan procedures not followed',
  '96': 'Non-covered charge(s)',
  '97': 'The benefit for this service is included in the payment/allowance for another service already adjudicated',
  '100': 'Payment made to patient/insured/responsible party/employer',
  '101': 'Predetermination: anticipated payment upon completion of services or claim adjudication',
  '102': 'Major Medical Adjustment',
  '103': 'Provider promotional discount',
  '104': 'Managed care withholding',
  '105': 'Tax withholding',
  '106': 'Patient payment option/election not in effect',
  '107': 'The related or qualifying claim/service was not identified on this claim',
  '108': 'Rent/purchase guidelines were not met',
  '109': 'Claim/service not covered by this payer/contractor',
  '110': 'Billing date predates service date',
  '111': 'Not covered unless the provider accepts assignment',
  '112': 'Service not furnished directly to the patient and/or not documented',
  '114': 'Procedure/product not approved by the Food and Drug Administration',
  '115': 'Procedure postponed, canceled, or delayed',
  '116': 'The advance indemnification notice signed by the patient did not comply with requirements',
  '117': 'Transportation is only covered to the closest facility that can provide the necessary care',
  '118': 'This service is considered to be part of a prior or associated service',
  '119': 'Benefit maximum for this time period or occurrence has been reached',
  '121': 'Indemnification adjustment - Loss or Gain',
  '122': 'Psychiatric reduction',
  '125': 'Submission/billing error(s)',
  '128': 'Newborn\'s services are covered in the mother\'s Allowance',
  '129': 'Prior processing information appears incorrect',
  '130': 'Claim submission fee',
  '131': 'Claim specific negotiated discount',
  '132': 'Prearranged demonstration project adjustment',
  '133': 'The disposition of this claim/service is pending further review',
  '134': 'Technical fees removed from charges',
  '135': 'Interim bill adjustment',
  '136': 'Failure to follow prior authorization guidelines',
  '137': 'Regulatory Surcharge/Fee',
  '138': 'Appeal procedures not followed',
  '139': 'Contracted funding agreement',
  '140': 'Patient/Insured health identification number and name do not match',
  '141': 'Claim spans eligible and ineligible periods of coverage, this is the reduction for the ineligible period',
  '142': 'Monthly Benefit Maximum has been reached',
  '143': 'Portion of payment deferred',
  '144': 'Incentive adjustment, e.g. preferred network/provider',
  '146': 'Diagnosis was invalid for the date(s) of service reported',
  '147': 'Provider contracted/negotiated rate expired or not on file',
  '148': 'Information from another provider was not provided or was insufficient/incomplete',
  '149': 'Lifetime Benefit Maximum has been reached for this service/benefit category',
  '150': 'Payer deems the information submitted does not support this level/type of service',
  '151': 'Payment adjusted because the payer deems the information submitted does not support this many services',
  '152': 'Payment adjusted because the payer deems the information does not support this length of service',
  '153': 'Payment adjusted because the payer deems the information submitted does not support this dosage',
  '154': 'Payment adjusted because the payer deems the information submitted does not support this day\'s supply',
  '155': 'This claim/service is not payable under our claims jurisdiction area',
  '157': 'Service/procedure is not authorized per your Clinical Trial Agreement',
  '158': 'Service/procedure is not authorized per governing clinical trial protocol',
  '159': 'Claim payment denied. Processing has been reverted to the original payer',
  '160': 'Injury/illness was the result of an activity that is a benefit exclusion',
  '161': 'Claim/Service denied. Claim/service submitted was previously payer on same date',
  '162': 'State-mandated Requirement for Property and Casualty',
  '163': 'Attachment/other documentation referenced on the claim was not received',
  '164': 'Attachment/other documentation referenced on the claim was not received in a timely fashion',
  '165': 'Referral absent or exceeded',
  '166': 'These services were submitted after the coverage terminated',
  '167': 'This (these) diagnosis(es) is (are) not covered',
  '169': 'Alternate benefit has been provided',
  '170': 'Payment is denied when performed/billed by this type of provider',
  '171': 'Payment is denied when performed/billed by this type of provider in this type of facility',
  '172': 'Payment is adjusted when performed/billed by a provider of this specialty',
  '173': 'Service/equipment/drug is not covered under the patient\'s current benefit plan',
  '174': 'Service was not prescribed by a physician',
  '175': 'Prescription is incomplete',
  '176': 'Prescription is not current',
  '177': 'Patient has not met the required eligibility requirements',
  '178': 'Claim does not satisfy medical review requirements',
  '179': 'Services are not covered/billable until patient reaches the age indicated in the contract',
  '180': 'Not billed as individual test',
  '181': 'Procedure code was invalid on the date of service',
  '182': 'Secondary payment amount',
  '183': 'The provider billed using an inpatient CPT code, but the services rendered were outside the scope of inpatient admission',
  '184': 'The prescribing/ordering provider is not eligible to prescribe/order the service billed',
  '185': 'Claim not processed',
  '186': 'Level of Care adjustment',
  '187': 'Consumer Spending Account payments',
  '188': 'Product/Service not Medically Appropriate',
  '189': 'Not otherwise classified (NOC) diagnosis code(s) or procedure code(s) required more specific information',
  '190': 'Payment is included in the allowance for a bundled procedure/service',
  '191': 'Not a payable procedure/service under this plan/provider contract',
  '192': 'Non-standard adjustment code from paper Remittance Advice',
  '193': 'Original payment decision is being maintained',
  '194': 'Anesthesia minutes exceeds maximum',
  '195': 'Refund issued to an erroneous priority payer for this claim/service',
  '197': 'Precertification/authorization/notification/pre-treatment absent',
  '198': 'Precertification/authorization/notification number is missing/invalid',
  '199': 'Revenue code and Procedure code do not match',
  '200': 'Expenses incurred during lapse in coverage',
  '201': 'Partial payment based on workers\' compensation fee schedule',
  '202': 'Non-covered personal comfort or convenience services',
  '203': 'Discontinued or reduced service',
  '204': 'This service/equipment/drug is not covered under the patient\'s current benefit plan',
  '205': 'Pharmacy discount',
  '206': 'National Drug Code (NDC) not eligible for rebate',
  '207': 'PPO provider premium rate was applied',
  '208': 'National Drug Code (NDC) is not found',
  '209': 'Claim denied for clinical policy reasons',
  '210': 'Payment adjusted because pre-certification/authorization not obtained',
  '211': 'National Drug Code (NDC) units of measure do not match',
  '212': 'Payment adjusted based on plan design when patient care is administered in an ambulatory surgical center',
  '213': 'Based on payer internal policy',
  '214': 'Claim denied because the medical record does not support the treatment',
  '215': 'Plan provision limiting reimbursement to the same time period treated previously',
  '216': 'New patient qualifications were not met',
  '217': 'Claim denied because patient was not seen by the referring provider',
  '218': 'The referring/ordering/prescribing provider is not eligible to refer/order/prescribe',
  '219': 'Based on extent of injury',
  '220': 'Claim denied because the referring/prescribing provider is not eligible',
  '221': 'Claim denied because provider has not met prior authorization requirements',
  '222': 'Payment adjusted based on Medical Loss Ratio (MLR) statutory fee schedule',
  '223': 'Payment denied based on administrative loss ratio (ALR) in effect',
  '224': 'Claim denied because patient has exceeded the benefit plan limits',
  '225': 'Denial based on condition documented as present on admission (POA)',
  '226': 'Information requested from patient or responsible party was not provided',
  '227': 'Payment adjusted based on date of death',
  '228': 'Denied by downstream entity',
  '229': 'Claim denied because the referring provider is not on the plan/network',
  '230': 'Claim denied because the ordering provider is not on the plan/network',
  '231': 'Claim denied because the prescribing provider is not on the plan/network',
  '232': 'Non-covered services due to regulatory requirement',
  '233': 'Denial based on services rendered after period of coverage',
  '234': 'Claim denied as the patient does not have a Qualifying Life Event (QLE)',
  '235': 'Amount exceeds daily patient limit',
  '236': 'Amount exceeds monthly patient limit',
  '237': 'Amount exceeds yearly patient limit',
  '238': 'Amount exceeds lifetime patient limit',
  '239': 'Charge is covered under a capitation/managed care arrangement',
  '240': 'Amount adjusted to the allowed amount per contract',
  '241': 'Non-covered services as defined in the benefit plan',
  '242': 'Charges denied. Self-administered drug is not covered',
  '243': 'Service not authorized by primary care physician',
  '244': 'Denied for failure to obtain pre-authorization',
  '245': 'Claim denied because provider failed to obtain certification',
  '246': 'Denied because this is not a teaching hospital',
  '247': 'Denied based on medical policy guidelines',
  '248': 'Denied based on patient incarceration status',
  '249': 'Denied based on pending coverage determination',
  '250': 'Claim denied as Federally Qualified Health Center (FQHC)',
  '251': 'Denied based on the provider group policy',
  '252': 'Administrative/Vendor discount',
  '253': 'Sequestration adjustment',
  '254': 'Prior Hospitalization or 30 Day Transfer Requirement not Met',
  '255': 'Claim denied as the service is part of an evaluation and management service',
  '256': 'Additional documentation is required to process your claim',
  '257': 'Claim denied as provider has already been reimbursed for this service through a bundled payment',
  '258': 'Denied for clinical editing',
  '259': 'Denied as the billing provider is not authorized to bill the claim',
  '260': 'Denied. Claim is under review for disposition determination',
  '261': 'The procedure code is not covered for the reported diagnosis',
  '262': 'Claim denied for clinical editing - bundling violation',
  '263': 'Benefit adjustment for hospital-acquired conditions or potential preventable conditions',
  '264': 'Precertification/authorization/notification present but diagnosis or service is not applicable to this payer',
  '265': 'Claim denied for clinical editing - add on procedure violation',
  '266': 'Claim denied because of an Emergency Department (ED) visit after a different ED visit',
  '267': 'Claim denied for clinical editing - mutually exclusive procedure violation',
  '268': 'Payment denied because service is already included in another billed code',
  '269': 'Claim denied for clinical editing - inappropriate use of modifier',
  '270': 'Claim denied for clinical editing - maximum units violation',
  '271': 'Claim denied based on claim/service eligibility criteria',
  '272': 'Coverage/program guidelines were not met',
  '273': 'Coverage/benefit has been denied or reduced because services were denied as not reasonable and necessary',
  '274': 'Fee schedule/payment/allowance adjustment',
  '275': 'Maximum regional reimbursement reached for this benefit period',
  '276': 'Services/Supplies provided as part of a clinical trial',
  '277': 'Fee on file does not apply to this entity',
  '278': 'Claim denied because coverage policy does not cover the service/supply',
  '279': 'Claim denied. Service/procedure is deemed experimental/investigational or unproven',
  '280': 'Denial for clinical policy reasons',
  '281': 'Denied as Patient Safety Organization (PSO) disclosure event',
  '282': 'Claim denied based on Comprehensive Error Rate Testing (CERT) audit',
  '283': 'Denied based on a prior appeals determination',
  '284': 'Claim denied because the procedure/drug was not performed with an applicable and covered lab procedure',
  '285': 'Denied for appeal submission does not meet formal filing requirements',
  '286': 'Adjustment based on federal law or administrative procedure',
  '287': 'Claim denied for clinical editing - medical visit violation',
  '288': 'Claim denied for clinical editing - supervision violation',
  '289': 'Service denied based on coding initiatives or special billing instructions',
  '290': 'Claim denied based on Medicare reimbursement limits',
  '291': 'Claim denied. Service is not Reasonable and Necessary',
  '292': 'Duplicate of a claim processed',
  '293': 'Denied based on the Transparency in Coverage Rule',
  '294': 'Claim denied because payment for service requires referral/treatment plan',
  '295': 'Claim denied based on prior claim adjudication',
  '296': 'Denial based on claim history',
  'P1': 'State-mandated Requirement for Property and Casualty, see Claim Payment Remarks Code',
  'P2': 'Not a work related injury/illness and target rule was not met',
  'P3': 'Workers\' Compensation case settled',
  'P4': 'Workers\' Compensation Medicare Set-Aside Arrangement',
  'P5': 'Workers\' Compensation case pending',
  'P6': 'Workers\' Compensation was Voluntarily Reinstated',
  'P7': 'Payment denied. The pharmacy is not in the network',
  'P8': 'Adjustment based on prior authorization',
  'P9': 'Payment adjusted based on the Higher-Weighted diagnosis-related group (DRG)',
  'P10': 'Payment denied. The pharmacy or prescriber is not in the network',
  'P11': 'Payment based on the physician specialty',
  'P12': 'Workers\' Compensation First Report of Injury not completed',
  'P13': 'Payment based on the provider type',
  'P14': 'Payment adjusted based on the 1-day payment policy',
  'P15': 'Claim denied as patient was not enrolled on the date of service',
  'P16': 'Payment denied. The payment is based on a prepayment review',
  'P17': 'Claim denied. Service/procedure requires prior approval',
  'P18': 'Claim denied as ineligible for coverage',
  'P19': 'Claim denied based on pre-payment audit results',
  'P20': 'Workers\' Compensation reserve exhausted',
  'P21': 'Claim denied based on an Authorization/Pre-certification/Prior Authorization denial',
  'P22': 'Claim denied based on Medicare fee schedule',
  'P23': 'Dental claim denied because treatment did not occur within the prescribed time frame',
  'B1': 'Non-covered visits',
  'B2': 'Covered visits',
  'B3': 'Covered only if authorized',
  'B4': 'Late filing penalty',
  'B5': 'Coverage/program guidelines were not met',
  'B6': 'Payment denied based on Benefit Maximum',
  'B7': 'Insurance reduces liability based on contract limitation',
  'B8': 'Alternative benefit payable',
  'B9': 'State-mandated benefit limitation',
  'B10': 'Allowed amount has been reduced because a component of the basic procedure was paid',
  'B11': 'Reduction/denial was based on a patient premium payment issue',
  'B12': 'Services are payable as a covered benefit under a supplemental insurance policy',
  'B13': 'Patient is responsible for the previously paid amount because of a coordination of benefits (COB) adjustment',
  'B14': 'Only one visit or consultation per physician per day is covered',
  'B15': 'This service/procedure is covered only when the number of remaining benefit/coverage is equal to or greater than the number of services provided',
  'B16': 'Payment denied/reduced because not all modifiers required on this claim were submitted',
  'B17': 'Claim denied as the medication is not on the formulary',
  'B18': 'Claim denied because the provider was out-of-network',
  'B19': 'Payment denied based on coordination of benefits',
  'B20': 'Claim denied based on Clinical Trials Network fee schedule',
  'B21': 'Payment denied based on prescription coverage plan',
  'B22': 'Claim denied because there is a gap in coverage',
  'B23': 'Claim denied because the patient is not enrolled in prescription coverage',
} as const;

/**
 * Common Remittance Advice Remark Codes (RARC)
 * Provide additional explanation for claim adjustments
 */
export const REMITTANCE_ADVICE_REMARK_CODES = {
  M1: 'X-ray not taken within the past 12 months or near enough to the start of treatment',
  M2: 'Not paid separately when the patient is an inpatient',
  M3: 'Equipment is the same or similar to equipment already being used',
  M4: 'Alert: This is the drug first available date',
  M5: 'Adjustment based on the physician specialty',
  M6: 'More than one Nurse or Registered Dietitian may not be paid.',
  M7: 'Missing/incomplete/invalid diagnosis or condition',
  M8: 'More than one evaluation and management code billed for this encounter',
  M9: 'An observation period payment is being made',
  M10: 'Payment reflects a demonstration project adjustment',
  M11: 'Alert: Provider identification number not found on this claim',
  M12: 'Diagnostic test or procedure not performed by the rendering provider',
  M13: 'Alert: The patient is on an approved clinical study',
  M14: 'Lab test(s) are not covered unless ordered by the personal physician',
  M15: 'Separately billed services/tests have been bundled',
  M16: 'Alert: See our website, provider manual, or call our provider service line for rate information',
  M17: 'Alert: Payment reflects the appropriate rate for observation services',
  M18: 'This claim requires manual review',
  M19: 'Missing/incomplete/invalid days or units of service',
  M20: 'Missing/incomplete/invalid National Drug Codes (NDC)',
  M21: 'Alert: This procedure has a Professional Component and a Technical Component',
  M22: 'Claim/service denied based on the date(s) of service',
  M23: 'Missing/incomplete/invalid patient name',
  M24: 'Missing/incomplete/invalid authorization number',
  M25: 'Alert: Additional information was sent to the review organization',
  M26: 'Claim lacks required final claim submission',
  M27: 'Subject to the patient\'s signature of the medical record',
  M28: 'This unit is not paid separately',
  M29: 'Missing/incomplete/invalid condition code',
  M30: 'Missing/incomplete/invalid other diagnosis',
  M31: 'Patient liability may be reduced/forgiven',
  M32: 'Alert: All services included in the Per Diem rate',
  M33: 'Alert: Incremental nursing facility claims',
  M34: 'Installment payment',
  M35: 'Alert: The medical record documentation submitted fails to support the level of service billed',
  M36: 'This claim/service has been adjudicated as a recurring item',
  M37: 'Alert: Missing date of birth',
  M38: 'Services for this rendering provider are not covered',
  M39: 'The submitted documentation does not support the level of this service',
  M40: 'Missing/incomplete/invalid dental codes',
  M41: 'Past filing date for the primary payer. Claim submitted late',
  M42: 'These services must be billed on a different claim form',
  M43: 'Electronic claim could not be processed. Please contact us for assistance',
  M44: 'Alert: No appeal rights. Decision is final',
  M45: 'Alert: Missing/invalid medical equipment certification',
  M46: 'Alert: Missing/invalid days of care',
  M47: 'Alert: Number of days/units more than allowed',
  M48: 'Alert: Payment for transport in connection with prior hospitalization',
  M49: 'Alert: Additional payment limited under law',
  M50: 'Missing/incomplete/invalid discharge diagnosis code',
  M51: 'Missing/incomplete/invalid procedure code(s)',
  M52: 'Missing/incomplete/invalid DRG code',
  M53: 'Claim cannot be processed',
  M54: 'Missing/incomplete/invalid initial treatment date',
  M55: 'Alert: Missing or invalid diagnosis/procedure code pairs',
  M56: 'Missing/incomplete/invalid ordering provider identifier',
  M57: 'Missing/incomplete/invalid provider name',
  M58: 'Payment denied based on an agreement between the provider and payer',
  M59: 'Alert: Additional information has been requested from the patient',
  M60: 'Missing/incomplete/invalid hospital admission diagnosis',
  M61: 'Missing/incomplete/invalid provider identifier',
  M62: 'Missing/incomplete/invalid service provider identification',
  M63: 'Missing/incomplete/invalid date',
  M64: 'Alert: Missing or invalid information',
  M65: 'Alert: Additional information regarding covered/non-covered services',
  M66: 'Alert: This decision could change when additional information is received',
  M67: 'Missing/incomplete/invalid National Drug Codes (NDC) qualifier/code/unit',
  M68: 'Missing/incomplete/invalid supporting documentation',
  M69: 'Alert: A copy of the procedure report must be retained',
  M70: 'Alert: Missing/invalid other subscriber/policy information',
  M71: 'Alert: Our records indicate you should submit this claim to the patient\'s other insurer',
  M72: 'Missing/incomplete/invalid supervising provider primary identifier',
  M73: 'Missing/incomplete/invalid assistant surgeon primary identifier',
  M74: 'Missing/incomplete/invalid claim frequency code',
  M75: 'Missing/incomplete/invalid narrative description of the unclassified drug or biological',
  M76: 'Missing/incomplete/invalid physician assistant primary identifier',
  M77: 'Missing/incomplete/invalid attending physician identifier',
  M78: 'Missing/incomplete/invalid referring provider identifier',
  M79: 'Missing/incomplete/invalid rendering provider primary identifier',
  M80: 'Not covered when performed during the same session as another procedure',
  M81: 'Alert: You may only appeal this decision in writing',
  M82: 'Missing/incomplete/invalid medical record number',
  M83: 'Alert: Service denied based on bundling rules',
  M84: 'Alert: Additional payment for the hospital-acquired condition is limited',
  M85: 'Patient identification information could not be found for the member',
  M86: 'Claim denied based on coordination of benefits (COB)',
  M87: 'Alert: The attachment submitted or payment for this item was previously requested',
  M88: 'Missing/incomplete/invalid other insured name',
  M89: 'Missing/incomplete/invalid referring provider/other source primary identifier',
  M90: 'Missing/incomplete/invalid other insured group name',
  M91: 'Missing/incomplete/invalid other insured birth date',
  M92: 'Missing/incomplete/invalid other insured gender',
  M93: 'Missing/incomplete/invalid other insured claim filing indicator',
  M94: 'Missing/incomplete/invalid credit or debit card information',
  M95: 'Missing/incomplete/invalid patient identifier',
  M96: 'Missing/incomplete/invalid billed amount',
  M97: 'Missing/incomplete/invalid tooth number/letter',
  M98: 'Missing/incomplete/invalid tooth surface',
  M99: 'Missing/incomplete/invalid oral cavity designation code',
  M100: 'Missing/incomplete/invalid replacement date for durable medical equipment',
  M101: 'Alert: This is a Medical Review determination',
  M102: 'Alert: Medical history does not support reported level of service',
  M103: 'Alert: Modifying diagnosis or procedure code to match clinical/payment rules',
  M104: 'Missing/incomplete/invalid purchased service information',
  M105: 'Missing/incomplete/invalid ambulance patient count',
  M106: 'Alert: Payment is based on the number of units indicated for the procedure code',
  M107: 'Missing/incomplete/invalid version, condition or revision level',
  M108: 'Alert: Payment has been reduced based on applicable regulations',
  M109: 'Claim denied based on peer review',
  M110: 'Not covered unless provider is contracted',
  M111: 'Missing/incomplete/invalid entity identifier',
  M112: 'Alert: Patient has been notified of the denied/adjusted service(s)',
  M113: 'Not covered unless approved through prior authorization',
  M114: 'Missing/incomplete/invalid facility type code',
  M115: 'Missing/incomplete/invalid authorization exception code',
  M116: 'Alert: Processed based on original claim submission',
  M117: 'Alert: Non-covered personal comfort services',
  M118: 'Missing/incomplete/invalid prior claim history',
  M119: 'Patient is not entitled to benefits for dates of service indicated',
  M120: 'Alert: If deemed to be appropriate, a care plan oversight fee may be paid',
  M121: 'Missing/incomplete/invalid patient liability amount',
  M122: 'Missing/incomplete/invalid procedure code modifier',
  M123: 'Missing/incomplete/invalid service facility primary identifier',
  M124: 'Missing/incomplete/invalid service provider taxonomy code',
  M125: 'Not payable by Medicare',
  M126: 'Service denied as not medically necessary based on the submitted records',
  M127: 'Missing/incomplete/invalid place of service code',
  M128: 'Missing/incomplete/invalid service facility address',
  M129: 'Alert: Prior claim information forwarded to another payer',
  M130: 'Alert: Additional information is required from another entity',
  M131: 'Alert: Claim must include itemized statement',
  M132: 'Missing/incomplete/invalid other coverage dates',
  M133: 'Alert: Claim adjustment amount is based on prior claim submission',
  M134: 'Missing/incomplete/invalid coverage amount',
  M135: 'Alert: Claim was submitted with incorrect patient liability amount',
  M136: 'Missing/incomplete/invalid patient responsibility percentage',
  M137: 'Part B coinsurance under a demonstration project',
  M138: 'Alert: This payer is secondary to Medicare',
  M139: 'Prior authorization was not obtained for this service',
  M140: 'Alert: Patient is responsible for deductible',
  M141: 'Missing/incomplete/invalid utilization management certification',
  M142: 'Missing/incomplete/invalid provider representative identifier',
  M143: 'Alert: Payment adjusted based on bundling/unbundling edits',
  M144: 'Pre-payment review of claim',
  M145: 'CARC 16 or 183 may be required when using this code',
  M146: 'Alert: Payment may include both professional and institutional components',
  M147: 'Alert: Award amount has been adjusted',
  M148: 'Missing/incomplete/invalid billing provider phone number',
  M149: 'Alert: Payment adjusted based on the number of referrals',
  M150: 'Missing/incomplete/invalid prescription number',
  MA01: 'If you do not agree with what we approved for these services, you may appeal our decision',
  MA02: 'If you do not agree with this determination, you have the right to appeal',
  MA03: 'Please see your Primary Explanation of Benefits for more details',
  MA04: 'Secondary payment cannot be calculated. Please submit payment information from the primary payer',
  MA05: 'Requested information was not received or was not received timely',
  MA07: 'The claim information has also been forwarded to Medicaid for supplemental payment',
  MA08: 'Claim rejected. The claim was not submitted on the correct claim form',
  MA09: 'Claim submitted as unassigned but the provider has an assignment',
  MA10: 'The provider has not filed an Advance Beneficiary Notice (ABN)',
  MA11: 'Alert: The claim has been returned to the sender',
  MA12: 'You have entered a claim in the Demonstration system with a missing or invalid NDC code',
  MA13: 'Alert: You may be subject to penalties if you bill the patient for amounts not reported',
  MA14: 'Alert: No additional payment for this claim',
  MA15: 'Claim submitted with missing or invalid provider billing number',
  MA16: 'The patient is covered by a State Pharmaceutical Assistance Program (SPAP)',
  MA17: 'Claim denied as adjusted or re-submitted claim',
  MA18: 'The claim has been submitted on wrong form type',
  MA19: 'Alert: Provider may not refuse to furnish services to an individual',
  MA20: 'Alert: Payment made from the electronic fund transfer (EFT) or debit card account',
  MA21: 'Claim rejected. 2 claims with same claim number were submitted',
  MA22: 'Alert: One or more services billed are non-covered',
  MA23: 'Alert: Payment adjusted based on the calculated fee schedule',
  MA24: 'Alert: Additional documentation is required. Please submit requested information',
  MA25: 'Alert: A patient may not be billed for this denied/adjusted service',
  MA26: 'Alert: The provider has not been paid for all services/supplies submitted',
  MA27: 'Missing/incomplete/invalid NPI',
  MA28: 'Alert: Claim denied based on Medicare Secondary Payer (MSP)',
  MA29: 'Missing/incomplete/invalid date of disability onset',
  MA30: 'Missing/incomplete/invalid type of disability',
  MA31: 'Service denied because equipment has not been demonstrated as effective',
  MA32: 'Alert: Service may be affected by prior denial or appeal',
  MA33: 'Missing/incomplete/invalid service provider secondary identifier',
  MA34: 'Missing/incomplete/invalid the health care institution certification number',
  MA35: 'Missing/incomplete/invalid provider representative primary identifier',
  MA36: 'Missing/incomplete/invalid claim submitted charges',
  MA37: 'Missing/incomplete/invalid referring provider secondary identifier',
  MA38: 'Alert: Please provide additional clinical/documentation to process this claim',
  MA39: 'Alert: Claim has been identified as a possible duplicate',
  MA40: 'Missing/incomplete/invalid information for the service provider that performed the service',
  N1: 'Alert: You may appeal this decision',
  N2: 'This allowance has been made in accordance with the most appropriate HCPCS code',
  N3: 'Missing/incomplete/invalid type of bill',
  N4: 'Missing/incomplete/invalid prior authorization number',
  N5: 'Service date is after the date of death',
  N6: 'Service date is more than 3 calendar years before the date of the request',
  N7: 'Alert: Missing/incomplete/invalid treatment authorization codes',
  N8: 'This claim may not be appealed',
  N9: 'Adjustment represents the estimated maximum allowable amount',
  N10: 'Additional payment is pending as claim review/audit is in progress',
  N11: 'Denial reversed per Medical Director review',
  N12: 'Charges denied per approved treatment plan',
  N13: 'Charges denied as they exceed your contracted maximum',
  N14: 'Payment pending for specialty provider network',
  N15: 'Services/charges subject to Medicaid restrictions',
  N16: 'Missing/incomplete/invalid place of service',
  N17: 'Alert: This service is separately reimbursed',
  N18: 'You must furnish and service this product for the time period specified in the contract',
  N19: 'Procedure code indicates DME or oxygen therapy services',
  N20: 'Missing/incomplete/invalid HPSA/bonus payment information',
  N21: 'Alert: Your claim contains service dates that fall before or after the benefit period',
  N22: 'Alert: Patient liability may be reduced/forgiven',
  N23: 'Missing/incomplete/invalid patient liability amount',
  N24: 'Missing/incomplete/invalid liability insurance policy and/or claim number',
  N25: 'Alert: Payment has been adjusted to correct/resolve a prior claim',
  N26: 'Alert: This service was included in a bundled payment',
  N27: 'Missing/incomplete/invalid treatment authorization code',
  N28: 'Patient is not entitled to Medicare',
  N29: 'No enrollment status for patient on claim',
  N30: 'The service in the claim has been identified as a duplicate',
  N31: 'The provided identifier is incorrect',
  N32: 'Alert: Payment has been reduced based on limitations in the contract',
  N33: 'Alert: No payment issued for one or more services',
  N34: 'This denial has been reviewed and will not be reversed',
  N35: 'Alert: This claim has been adjudicated for payment under the demonstration project',
  N36: 'Alert: Lifetime reserve days could apply to this claim',
  N37: 'Missing/incomplete/invalid eligibility dates',
  N38: 'The referring/ordering provider is not eligible to refer/order the services billed',
  N39: 'Claim/service denied based on the patient\'s eligibility',
  N40: 'Alert: This payment has been made from the Reserve Account',
  N41: 'Rejection pending contract compliance review',
  N42: 'Alert: Payment is being made for professional services only',
  N43: 'Alert: Please verify your billing information before resubmitting',
  N44: 'Alert: This is a one-time settlement payment',
  N45: 'Payment denied for a duplicate claim',
  N46: 'Alert: Medical services not provided for this patient',
  N47: 'Alert: The charge(s) are for non-covered services',
  N48: 'This claim has been adjusted to reflect an approved or previously allowed amount',
  N49: 'Alert: These are not covered services',
  N50: 'Missing/incomplete/invalid end-stage renal disease (ESRD) information',
  N51: 'Payment denied. A valid referral authorization is required',
  N52: 'Missing/incomplete/invalid referring provider information',
  N53: 'Alert: This was processed as an outpatient claim',
  N54: 'This claim requires review before payment can be made',
  N55: 'Claims for these services are not covered by this payer/plan',
  N56: 'Missing/incomplete/invalid provider network information',
  N57: 'Missing/incomplete/invalid patient gender',
  N58: 'This claim has been forwarded to the primary payer',
  N59: 'Missing/incomplete/invalid patient DOB',
  N60: 'Alert: The claim is being processed. The outcome will be sent separately',
  N61: 'Missing/incomplete/invalid billing provider taxonomy code',
  N62: 'Alert: This is an unassigned claim',
  N63: 'Missing/incomplete/invalid hospital information',
  N64: 'Claim received after deadline',
  N65: 'Procedure code changed based on National Correct Coding Initiative (NCCI)',
  N66: 'Alert: The service was reprocessed because the original payment was incorrect',
  N67: 'Alert: Previous claim submitted separately as an adjustment',
  N68: 'Alert: The payment for this service includes the amount for the facility fee',
  N69: 'The service is not covered for this patient',
  N70: 'Alert: Payment for physician services could not be determined',
  N71: 'Alert: Claim submitted with an incorrect or missing NDC code',
  N72: 'Alert: Awaiting additional information about this patient',
  N73: 'Alert: Patient must submit additional documentation',
  N74: 'Claim payment adjusted according to your contract',
  N75: 'Missing/incomplete/invalid claim type code',
  N76: 'Missing/incomplete/invalid documentation/records',
  N77: 'Missing/incomplete/invalid other insured/subscriber name',
  N78: 'Missing/incomplete/invalid diagnostic test results',
  N79: 'Missing/incomplete/invalid service authorization/exemption code',
  N80: 'This is a one-time penalty for not meeting prior authorization/pre-certification requirements',
  N81: 'Alert: Additional documentation may be required for this service',
  N82: 'Alert: This payment reflects a penalty for not meeting pre-certification/prior authorization guidelines',
  N83: 'Missing/incomplete/invalid other covered insurance information',
  N84: 'Missing/incomplete/invalid accident information',
  N85: 'Missing/incomplete/invalid referring provider NPI',
  N86: 'Missing/incomplete/invalid billing provider NPI',
  N87: 'Missing/incomplete/invalid date of admission',
  N88: 'This claim was adjusted based on a prior determination',
  N89: 'Alert: This service is limited to a maximum number of times per year',
  N90: 'Missing/incomplete/invalid medical record',
  N91: 'Claim has been forwarded to the payer based on the patient\'s benefit plan',
  N92: 'Missing/incomplete/invalid pathology/lab specimen',
  N93: 'Claim has been forwarded to Medicare for further processing',
  N94: 'Claim has been forwarded to Medicaid for further processing',
  N95: 'This claim/service does not meet the definition of emergency services',
  N96: 'This claim contains services that are not covered because they are out of network',
  N97: 'The patient is eligible for benefits under another health plan',
  N98: 'Payment denied. Services are covered by a Workers\' Compensation program',
  N99: 'Missing/incomplete/invalid date of injury/illness',
  N100: 'Missing/incomplete/invalid emergency ambulance certification',
  N101: 'Payment denied. The patient is not eligible for this service',
  N102: 'This claim does not qualify for payment based on plan exclusions',
  N103: 'Alert: A deductible and/or coinsurance may apply to this claim',
  N104: 'Alert: This patient is responsible for the deductible/copayment for this service',
  N105: 'Missing/incomplete/invalid claim frequency type code',
  N106: 'Alert: Payment has been withheld for administrative purposes',
  N107: 'Alert: Maximum benefits have been exhausted',
  N108: 'Alert: Payment reduced based on allowable limits',
  N109: 'Alert: Overpayment has been adjusted',
  N110: 'Missing/incomplete/invalid subscriber relationship code',
  N111: 'No appeal rights. Claim denied due to contract limit',
  N112: 'Claim denied based on limitation of benefits in effect',
  N113: 'Prior authorization was obtained for a different service/provider',
  N114: 'Alert: Payment based on a rate negotiated with your organization',
  N115: 'This decision was based on a local policy',
  N116: 'This claim was denied because the documentation did not support medical necessity',
  N117: 'Payment based on an interim rate',
  N118: 'This payment reflects a cap on the amount payable',
  N119: 'Payment adjusted based on contract rates in effect',
  N120: 'Payment has been denied for duplicate charge',
  N121: 'Medicare does not pay for items/services ordered by an excluded provider',
  N122: 'Alert: The service was split because it was billed for more than one day',
  N123: 'This claim will not be paid because your facility is not certified',
  N124: 'Payment denied based on precertification requirements not being met',
  N125: 'Payment denied based on documentation or clinical requirements',
  N126: 'Alert: This is an interim payment',
  N127: 'Payment includes an amount for a mandated benefit',
  N128: 'Alert: The service has been approved',
  N129: 'Alert: Prior authorization was obtained for this service',
  N130: 'Claim denied based on pre-admission screening',
  N131: 'Alert: Payment has been made in full based on current plan limits',
  N132: 'Alert: Allowed amount has been adjusted',
  N133: 'Alert: Claim contains service dates that are after the date of death',
  N134: 'Alert: This service requires prior authorization',
  N135: 'Alert: Records do not support the level of service billed',
  N136: 'Alert: Billed laboratory services do not meet certification requirements',
  N137: 'Alert: Alert: Payment is being denied/reduced based on provider type',
  N138: 'Alert: Payment is being made based on review of the submitted information',
  N139: 'Alert: The patient\'s certification is being sent to the provider for signature',
  N140: 'Alert: Payment has been reduced based on facility fee schedule',
  N141: 'Alert: Patient\'s insurance has changed',
  N142: 'Alert: Payment adjusted based on rates for services rendered',
  N143: 'Alert: Payment includes provider bonus/incentive',
  N144: 'Alert: Payment reflects maximum allowable under the contract',
  N145: 'Alert: Claim processed for payment under negotiated rates',
  N146: 'Alert: Payment made for physician services',
  N147: 'Alert: This is payment for an authorized provider',
  N148: 'Alert: Patient liability is based on an approved amount',
  N149: 'Alert: Claim processed as out-of-network',
  N150: 'Alert: Claim has been processed',
} as const;

export type ClaimAdjustmentGroup = keyof typeof CLAIM_ADJUSTMENT_GROUPS;
export type ClaimAdjustmentReasonCode = keyof typeof CLAIM_ADJUSTMENT_REASON_CODES;
export type RemittanceAdviceRemarkCode = keyof typeof REMITTANCE_ADVICE_REMARK_CODES;
