/*
 * Copyright (c) Velocity BPA, LLC
 * Licensed under the Business Source License 1.1
 * Commercial use requires a separate commercial license.
 * See LICENSE file for details.
 */

/**
 * Healthcare Transaction Types and Codes
 * 
 * Standardized codes for healthcare transactions, place of service,
 * taxonomy, and other reference data
 */

/**
 * Place of Service Codes (CMS)
 * Two-digit codes indicating the location where services were rendered
 */
export const PLACE_OF_SERVICE_CODES = {
  '01': 'Pharmacy',
  '02': 'Telehealth Provided Other than in Patient\'s Home',
  '03': 'School',
  '04': 'Homeless Shelter',
  '05': 'Indian Health Service Free-Standing Facility',
  '06': 'Indian Health Service Provider-Based Facility',
  '07': 'Tribal 638 Free-Standing Facility',
  '08': 'Tribal 638 Provider-Based Facility',
  '09': 'Prison/Correctional Facility',
  '10': 'Telehealth Provided in Patient\'s Home',
  '11': 'Office',
  '12': 'Home',
  '13': 'Assisted Living Facility',
  '14': 'Group Home',
  '15': 'Mobile Unit',
  '16': 'Temporary Lodging',
  '17': 'Walk-in Retail Health Clinic',
  '18': 'Place of Employment - Worksite',
  '19': 'Off Campus - Outpatient Hospital',
  '20': 'Urgent Care Facility',
  '21': 'Inpatient Hospital',
  '22': 'On Campus - Outpatient Hospital',
  '23': 'Emergency Room - Hospital',
  '24': 'Ambulatory Surgical Center',
  '25': 'Birthing Center',
  '26': 'Military Treatment Facility',
  '27': 'Outreach Site/Street',
  '31': 'Skilled Nursing Facility',
  '32': 'Nursing Facility',
  '33': 'Custodial Care Facility',
  '34': 'Hospice',
  '41': 'Ambulance - Land',
  '42': 'Ambulance - Air or Water',
  '49': 'Independent Clinic',
  '50': 'Federally Qualified Health Center',
  '51': 'Inpatient Psychiatric Facility',
  '52': 'Psychiatric Facility - Partial Hospitalization',
  '53': 'Community Mental Health Center',
  '54': 'Intermediate Care Facility - Mentally Retarded',
  '55': 'Residential Substance Abuse Treatment Facility',
  '56': 'Psychiatric Residential Treatment Center',
  '57': 'Non-residential Substance Abuse Treatment Facility',
  '58': 'Non-residential Opioid Treatment Facility',
  '60': 'Mass Immunization Center',
  '61': 'Comprehensive Inpatient Rehabilitation Facility',
  '62': 'Comprehensive Outpatient Rehabilitation Facility',
  '65': 'End-Stage Renal Disease Treatment Facility',
  '71': 'Public Health Clinic',
  '72': 'Rural Health Clinic',
  '81': 'Independent Laboratory',
  '99': 'Other Place of Service',
} as const;

/**
 * Type of Bill Codes (UB-04)
 * Four-digit codes for institutional claims
 */
export const TYPE_OF_BILL_CODES = {
  // Hospital - Inpatient
  '0111': 'Hospital Inpatient (Including Medicare Part A) - Admit Through Discharge',
  '0112': 'Hospital Inpatient - Interim - First Claim',
  '0113': 'Hospital Inpatient - Interim - Continuing Claim',
  '0114': 'Hospital Inpatient - Interim - Last Claim',
  '0117': 'Hospital Inpatient - Replacement',
  '0118': 'Hospital Inpatient - Void/Cancel',
  
  // Hospital - Outpatient
  '0131': 'Hospital Outpatient - Admit Through Discharge',
  '0132': 'Hospital Outpatient - Interim - First Claim',
  '0133': 'Hospital Outpatient - Interim - Continuing Claim',
  '0134': 'Hospital Outpatient - Interim - Last Claim',
  '0137': 'Hospital Outpatient - Replacement',
  '0138': 'Hospital Outpatient - Void/Cancel',
  
  // Skilled Nursing Facility
  '0211': 'SNF Inpatient (Including Medicare Part A) - Admit Through Discharge',
  '0212': 'SNF Inpatient - Interim - First Claim',
  '0213': 'SNF Inpatient - Interim - Continuing Claim',
  '0214': 'SNF Inpatient - Interim - Last Claim',
  '0217': 'SNF Inpatient - Replacement',
  '0218': 'SNF Inpatient - Void/Cancel',
  
  // Home Health
  '0321': 'Home Health - Admit Through Discharge',
  '0322': 'Home Health - Interim - First Claim',
  '0323': 'Home Health - Interim - Continuing Claim',
  '0324': 'Home Health - Interim - Last Claim',
  '0327': 'Home Health - Replacement',
  '0328': 'Home Health - Void/Cancel',
  
  // Hospice
  '0811': 'Hospice - Hospital - Admit Through Discharge',
  '0812': 'Hospice - Hospital - Interim - First Claim',
  '0813': 'Hospice - Hospital - Interim - Continuing Claim',
  '0814': 'Hospice - Hospital - Interim - Last Claim',
  '0817': 'Hospice - Hospital - Replacement',
  '0818': 'Hospice - Hospital - Void/Cancel',
  '0821': 'Hospice - Non-Hospital - Admit Through Discharge',
  '0822': 'Hospice - Non-Hospital - Interim - First Claim',
  '0823': 'Hospice - Non-Hospital - Interim - Continuing Claim',
  '0824': 'Hospice - Non-Hospital - Interim - Last Claim',
  '0827': 'Hospice - Non-Hospital - Replacement',
  '0828': 'Hospice - Non-Hospital - Void/Cancel',
  
  // Ambulatory Surgery Center
  '0831': 'ASC - Admit Through Discharge',
  '0837': 'ASC - Replacement',
  '0838': 'ASC - Void/Cancel',
} as const;

/**
 * Revenue Codes (UB-04)
 * Four-digit codes for specific services and accommodations
 */
export const REVENUE_CODES = {
  // Room and Board
  '0100': 'All-Inclusive Room and Board Plus Ancillary',
  '0101': 'All-Inclusive Room and Board Plus Ancillary - General',
  '0110': 'Room and Board - Private (1 Bed) - General',
  '0111': 'Room and Board - Private (1 Bed) - Medical/Surgical/GYN',
  '0112': 'Room and Board - Private (1 Bed) - OB',
  '0113': 'Room and Board - Private (1 Bed) - Pediatric',
  '0114': 'Room and Board - Private (1 Bed) - Psychiatric',
  '0116': 'Room and Board - Private (1 Bed) - Detox',
  '0117': 'Room and Board - Private (1 Bed) - Oncology',
  '0120': 'Room and Board - Semi-Private (2 Beds) - General',
  '0121': 'Room and Board - Semi-Private (2 Beds) - Medical/Surgical/GYN',
  '0122': 'Room and Board - Semi-Private (2 Beds) - OB',
  '0123': 'Room and Board - Semi-Private (2 Beds) - Pediatric',
  '0124': 'Room and Board - Semi-Private (2 Beds) - Psychiatric',
  '0126': 'Room and Board - Semi-Private (2 Beds) - Detox',
  '0127': 'Room and Board - Semi-Private (2 Beds) - Oncology',
  
  // ICU
  '0200': 'Intensive Care - General',
  '0201': 'Intensive Care - Surgical',
  '0202': 'Intensive Care - Medical',
  '0203': 'Intensive Care - Pediatric',
  '0204': 'Intensive Care - Psychiatric',
  '0206': 'Intensive Care - Intermediate ICU',
  '0207': 'Intensive Care - Burn Care',
  '0208': 'Intensive Care - Trauma',
  '0210': 'Coronary Care - General',
  '0211': 'Coronary Care - Myocardial Infarction',
  '0212': 'Coronary Care - Pulmonary Care',
  '0213': 'Coronary Care - Heart Transplant',
  '0214': 'Coronary Care - Intermediate CCU',
  
  // Pharmacy
  '0250': 'Pharmacy - General',
  '0251': 'Pharmacy - Generic Drugs',
  '0252': 'Pharmacy - Non-Generic Drugs',
  '0253': 'Pharmacy - Take Home Drugs',
  '0254': 'Pharmacy - Drugs Incident to Other Diagnostic Services',
  '0255': 'Pharmacy - Drugs Incident to Radiology',
  '0256': 'Pharmacy - Experimental Drugs',
  '0257': 'Pharmacy - Non-Prescription',
  '0258': 'Pharmacy - IV Solutions',
  '0259': 'Pharmacy - Other Pharmacy',
  
  // Laboratory
  '0300': 'Laboratory - General',
  '0301': 'Laboratory - Chemistry',
  '0302': 'Laboratory - Immunology',
  '0303': 'Laboratory - Renal Patient (Home)',
  '0304': 'Laboratory - Non-Routine Dialysis',
  '0305': 'Laboratory - Hematology',
  '0306': 'Laboratory - Bacteriology and Microbiology',
  '0307': 'Laboratory - Urology',
  '0309': 'Laboratory - Other Laboratory',
  '0310': 'Laboratory Pathology - General',
  '0311': 'Laboratory Pathology - Cytology',
  '0312': 'Laboratory Pathology - Histology',
  '0314': 'Laboratory Pathology - Biopsy',
  '0319': 'Laboratory Pathology - Other',
  
  // Radiology
  '0320': 'Radiology - Diagnostic - General',
  '0321': 'Radiology - Diagnostic - Angiocardiography',
  '0322': 'Radiology - Diagnostic - Arthrography',
  '0323': 'Radiology - Diagnostic - Arteriography',
  '0324': 'Radiology - Diagnostic - Chest X-Ray',
  '0329': 'Radiology - Diagnostic - Other',
  '0330': 'Radiology - Therapeutic - General',
  '0333': 'Radiology - Therapeutic - Radiation Therapy',
  '0339': 'Radiology - Therapeutic - Other',
  '0340': 'Nuclear Medicine - General',
  '0341': 'Nuclear Medicine - Diagnostic',
  '0342': 'Nuclear Medicine - Therapeutic',
  '0343': 'Nuclear Medicine - Diagnostic Radiopharmaceuticals',
  '0344': 'Nuclear Medicine - Therapeutic Radiopharmaceuticals',
  '0350': 'CT Scan - General',
  '0351': 'CT Scan - Head',
  '0352': 'CT Scan - Body',
  '0359': 'CT Scan - Other',
  
  // Operating Room
  '0360': 'Operating Room Services - General',
  '0361': 'Operating Room Services - Minor Surgery',
  '0362': 'Operating Room Services - Organ Transplant - Other Than Kidney',
  '0367': 'Operating Room Services - Kidney Transplant',
  '0369': 'Operating Room Services - Other',
  '0370': 'Anesthesia - General',
  '0371': 'Anesthesia - Incident to Radiology',
  '0372': 'Anesthesia - Incident to Other Diagnostic Services',
  '0374': 'Anesthesia - Acupuncture',
  '0379': 'Anesthesia - Other',
  
  // Blood and Blood Products
  '0380': 'Blood - General',
  '0381': 'Blood - Packed Red Cells',
  '0382': 'Blood - Whole Blood',
  '0383': 'Blood - Plasma',
  '0384': 'Blood - Platelets',
  '0385': 'Blood - Leukocytes',
  '0386': 'Blood - Other Components',
  '0387': 'Blood - Other Derivatives (Cryoprecipitates)',
  '0389': 'Blood - Other Blood',
  '0390': 'Blood Storage and Processing - General',
  '0391': 'Blood Storage and Processing - Blood Administration',
  '0399': 'Blood Storage and Processing - Other',
  
  // Medical/Surgical Supplies
  '0270': 'Medical/Surgical Supplies - General',
  '0271': 'Medical/Surgical Supplies - Non-Sterile',
  '0272': 'Medical/Surgical Supplies - Sterile',
  '0273': 'Medical/Surgical Supplies - Take Home',
  '0274': 'Medical/Surgical Supplies - Prosthetic/Orthotic Devices',
  '0275': 'Medical/Surgical Supplies - Pacemaker',
  '0276': 'Medical/Surgical Supplies - Intraocular Lens',
  '0278': 'Medical/Surgical Supplies - Other Implants',
  '0279': 'Medical/Surgical Supplies - Other',
  
  // Emergency Room
  '0450': 'Emergency Room - General',
  '0451': 'Emergency Room - EMTALA Emergency Screening',
  '0452': 'Emergency Room - ER Beyond EMTALA Screening',
  '0456': 'Emergency Room - Urgent Care',
  '0459': 'Emergency Room - Other',
  
  // Clinic
  '0510': 'Clinic - General',
  '0512': 'Clinic - Dental',
  '0513': 'Clinic - Psychiatric',
  '0514': 'Clinic - OB-GYN',
  '0515': 'Clinic - Pediatric',
  '0516': 'Clinic - Urgent Care',
  '0517': 'Clinic - Family Practice',
  '0519': 'Clinic - Other',
  
  // Physical Therapy
  '0420': 'Physical Therapy - General',
  '0421': 'Physical Therapy - Visit Charge',
  '0422': 'Physical Therapy - Hourly Charge',
  '0423': 'Physical Therapy - Group Rate',
  '0424': 'Physical Therapy - Evaluation or Re-Evaluation',
  '0429': 'Physical Therapy - Other',
  
  // Occupational Therapy
  '0430': 'Occupational Therapy - General',
  '0431': 'Occupational Therapy - Visit Charge',
  '0432': 'Occupational Therapy - Hourly Charge',
  '0433': 'Occupational Therapy - Group Rate',
  '0434': 'Occupational Therapy - Evaluation or Re-Evaluation',
  '0439': 'Occupational Therapy - Other',
  
  // Speech-Language Pathology
  '0440': 'Speech-Language Pathology - General',
  '0441': 'Speech-Language Pathology - Visit Charge',
  '0442': 'Speech-Language Pathology - Hourly Charge',
  '0443': 'Speech-Language Pathology - Group Rate',
  '0444': 'Speech-Language Pathology - Evaluation or Re-Evaluation',
  '0449': 'Speech-Language Pathology - Other',
  
  // Cardiology
  '0480': 'Cardiology - General',
  '0481': 'Cardiology - Cardiac Catheterization Lab',
  '0482': 'Cardiology - Stress Test',
  '0483': 'Cardiology - Echocardiology',
  '0489': 'Cardiology - Other',
  
  // Ambulance
  '0540': 'Ambulance - General',
  '0541': 'Ambulance - Supplies',
  '0542': 'Ambulance - Medical Transport',
  '0543': 'Ambulance - Heart Mobile',
  '0544': 'Ambulance - Oxygen',
  '0545': 'Ambulance - Air Ambulance',
  '0546': 'Ambulance - Neonatal Ambulance',
  '0547': 'Ambulance - Pharmacy',
  '0548': 'Ambulance - EKG Transmission',
  '0549': 'Ambulance - Other',
  
  // DME
  '0290': 'Durable Medical Equipment - General',
  '0291': 'Durable Medical Equipment - Rental',
  '0292': 'Durable Medical Equipment - Purchase of New',
  '0293': 'Durable Medical Equipment - Purchase of Used',
  '0294': 'Durable Medical Equipment - Supplies/Drugs for DME',
  '0299': 'Durable Medical Equipment - Other',
  
  // Professional Fees
  '0960': 'Professional Fees - General',
  '0961': 'Professional Fees - Psychiatric',
  '0962': 'Professional Fees - Ophthalmology',
  '0963': 'Professional Fees - Anesthesiologist (MD)',
  '0964': 'Professional Fees - Anesthetist (CRNA)',
  '0969': 'Professional Fees - Other',
  
  // Observation
  '0760': 'Observation Room - General',
  '0762': 'Observation Room - Observation Hours',
  '0769': 'Observation Room - Other',
  
  // MRI
  '0610': 'MRI - General',
  '0611': 'MRI - Brain (Including Brainstem)',
  '0612': 'MRI - Spinal Cord (Including Spine)',
  '0614': 'MRI - Other MRI',
  '0615': 'MRI - Head and Neck',
  '0616': 'MRI - Lower Extremities',
  '0618': 'MRI - Other MRI',
  '0619': 'MRI - Other',
} as const;

/**
 * Taxonomy Codes (Selected Common Specialties)
 * Provider specialty classification codes
 */
export const TAXONOMY_CODES = {
  // Physicians
  '207Q00000X': 'Family Medicine',
  '207R00000X': 'Internal Medicine',
  '207RC0000X': 'Cardiovascular Disease',
  '207RG0100X': 'Gastroenterology',
  '207RH0000X': 'Hematology',
  '207RI0001X': 'Clinical & Laboratory Immunology',
  '207RI0008X': 'Hepatology',
  '207RI0011X': 'Interventional Cardiology',
  '207RI0200X': 'Infectious Disease',
  '207RN0300X': 'Nephrology',
  '207RP1001X': 'Pulmonary Disease',
  '207RR0500X': 'Rheumatology',
  '207RS0012X': 'Sleep Medicine',
  '207V00000X': 'Obstetrics & Gynecology',
  '207VE0102X': 'Reproductive Endocrinology',
  '207VG0400X': 'Gynecology',
  '207VM0101X': 'Maternal & Fetal Medicine',
  '207W00000X': 'Ophthalmology',
  '207X00000X': 'Orthopaedic Surgery',
  '207XS0106X': 'Hand Surgery',
  '207XS0114X': 'Adult Reconstructive Orthopaedic Surgery',
  '207XS0117X': 'Orthopaedic Surgery of the Spine',
  '207Y00000X': 'Otolaryngology',
  '208000000X': 'Pediatrics',
  '2080P0201X': 'Pediatric Allergy/Immunology',
  '2080P0202X': 'Pediatric Cardiology',
  '2080P0203X': 'Pediatric Critical Care Medicine',
  '2080P0204X': 'Pediatric Emergency Medicine',
  '2080P0205X': 'Pediatric Endocrinology',
  '2080P0206X': 'Pediatric Gastroenterology',
  '2080P0207X': 'Pediatric Hematology-Oncology',
  '2080P0208X': 'Pediatric Infectious Diseases',
  '2080P0210X': 'Pediatric Nephrology',
  '2080P0214X': 'Pediatric Pulmonology',
  '2080P0216X': 'Pediatric Rheumatology',
  '208100000X': 'Physical Medicine & Rehabilitation',
  '2081P0004X': 'Spinal Cord Injury Medicine',
  '2081P0010X': 'Pediatric Rehabilitation Medicine',
  '2081P2900X': 'Pain Medicine',
  '2081S0010X': 'Sports Medicine',
  '208200000X': 'Plastic Surgery',
  '2082S0099X': 'Plastic Surgery Within the Head and Neck',
  '2082S0105X': 'Surgery of the Hand',
  '208600000X': 'Surgery',
  '2086S0102X': 'Surgical Critical Care',
  '2086S0105X': 'Surgery of the Hand',
  '2086S0120X': 'Pediatric Surgery',
  '2086S0122X': 'Plastic and Reconstructive Surgery',
  '2086S0127X': 'Trauma Surgery',
  '2086S0129X': 'Vascular Surgery',
  '208G00000X': 'Thoracic Surgery (Cardiothoracic Vascular Surgery)',
  '208800000X': 'Urology',
  '2088P0231X': 'Pediatric Urology',
  '208C00000X': 'Colon & Rectal Surgery',
  '208D00000X': 'General Practice',
  '208M00000X': 'Hospitalist',
  '208U00000X': 'Clinical Pharmacology',
  '208VP0000X': 'Pain Medicine',
  '208VP0014X': 'Interventional Pain Medicine',
  '209800000X': 'Legal Medicine',
  
  // Nursing
  '363L00000X': 'Nurse Practitioner',
  '363LA2100X': 'Acute Care Nurse Practitioner',
  '363LA2200X': 'Adult Health Nurse Practitioner',
  '363LC0200X': 'Critical Care Medicine Nurse Practitioner',
  '363LC1500X': 'Community Health Nurse Practitioner',
  '363LF0000X': 'Family Nurse Practitioner',
  '363LG0600X': 'Gerontology Nurse Practitioner',
  '363LN0000X': 'Neonatal Nurse Practitioner',
  '363LN0005X': 'Critical Care Neonatal Nurse Practitioner',
  '363LP0200X': 'Pediatric Nurse Practitioner',
  '363LP0222X': 'Pediatric Primary Care Nurse Practitioner',
  '363LP0808X': 'Psychiatric/Mental Health Nurse Practitioner',
  '363LP1700X': 'Perinatal Nurse Practitioner',
  '363LP2300X': 'Primary Care Nurse Practitioner',
  '363LS0200X': 'School Nurse Practitioner',
  '363LW0102X': 'Women\'s Health Nurse Practitioner',
  '363LX0001X': 'Obstetrics & Gynecology Nurse Practitioner',
  '363LX0106X': 'Occupational Health Nurse Practitioner',
  '364S00000X': 'Clinical Nurse Specialist',
  '367500000X': 'Nurse Anesthetist, Certified Registered',
  '367A00000X': 'Advanced Practice Midwife',
  '367H00000X': 'Anesthesiologist Assistant',
  
  // Physician Assistants
  '363A00000X': 'Physician Assistant',
  '363AM0700X': 'Physician Assistant - Medical',
  '363AS0400X': 'Physician Assistant - Surgical',
  
  // Mental Health
  '101Y00000X': 'Counselor',
  '101YA0400X': 'Addiction (Substance Use Disorder) Counselor',
  '101YM0800X': 'Mental Health Counselor',
  '101YP1600X': 'Pastoral Counselor',
  '101YP2500X': 'Professional Counselor',
  '101YS0200X': 'School Counselor',
  '102L00000X': 'Psychoanalyst',
  '102X00000X': 'Poetry Therapist',
  '103G00000X': 'Clinical Neuropsychologist',
  '103GC0700X': 'Clinical Neuropsychologist - Deactivated',
  '103K00000X': 'Behavioral Analyst',
  '103T00000X': 'Psychologist',
  '103TA0400X': 'Psychologist - Addiction (Substance Use Disorder)',
  '103TA0700X': 'Psychologist - Adult Development & Aging',
  '103TB0200X': 'Psychologist - Cognitive & Behavioral',
  '103TC0700X': 'Psychologist - Clinical',
  '103TC1900X': 'Psychologist - Counseling',
  '103TC2200X': 'Psychologist - Clinical Child & Adolescent',
  '103TE1000X': 'Psychologist - Educational',
  '103TE1100X': 'Psychologist - Exercise & Sports',
  '103TF0000X': 'Psychologist - Family',
  '103TF0200X': 'Psychologist - Forensic',
  '103TH0100X': 'Psychologist - Health',
  '103TM1700X': 'Psychologist - Men & Masculinity',
  '103TM1800X': 'Psychologist - Mental Retardation & Developmental Disabilities',
  '103TP0016X': 'Psychologist - Prescribing (Medical)',
  '103TP0814X': 'Psychologist - Psychoanalysis',
  '103TP2700X': 'Psychologist - Psychotherapy',
  '103TP2701X': 'Psychologist - Group Psychotherapy',
  '103TR0400X': 'Psychologist - Rehabilitation',
  '103TS0200X': 'Psychologist - School',
  '103TW0100X': 'Psychologist - Women',
  '104100000X': 'Social Worker',
  '1041C0700X': 'Social Worker - Clinical',
  '1041S0200X': 'Social Worker - School',
  
  // Facilities
  '282N00000X': 'General Acute Care Hospital',
  '282NC0060X': 'Critical Access Hospital',
  '282NC2000X': 'Children\'s Hospital',
  '282NR1301X': 'Rural Acute Care Hospital',
  '282NW0100X': 'Women\'s Hospital',
  '283Q00000X': 'Psychiatric Hospital',
  '283X00000X': 'Rehabilitation Hospital',
  '284300000X': 'Special Hospital',
  '286500000X': 'Military Hospital',
  '287300000X': 'Christian Science Sanatorium',
  '291900000X': 'Military Clinical Medical Laboratory',
  '291U00000X': 'Clinical Medical Laboratory',
  '292200000X': 'Dental Laboratory',
  '293D00000X': 'Physiological Laboratory',
  '302F00000X': 'Exclusive Provider Organization',
  '302R00000X': 'Health Maintenance Organization',
  '305R00000X': 'Preferred Provider Organization',
  '305S00000X': 'Point of Service',
  '310400000X': 'Assisted Living Facility',
  '310500000X': 'Intermediate Care Facility, Mental Illness',
  '311500000X': 'Alzheimer Center (Dementia Center)',
  '311Z00000X': 'Custodial Care Facility',
  '313M00000X': 'Nursing Facility/Intermediate Care Facility',
  '314000000X': 'Skilled Nursing Facility',
  '315D00000X': 'Hospice, Inpatient',
  '315P00000X': 'Intermediate Care Facility, Mentally Retarded',
  '317400000X': 'Christian Science Facility',
  '320600000X': 'Residential Treatment Facility, Mental Retardation and/or Developmental Disabilities',
  '320700000X': 'Residential Treatment Facility, Physical Disabilities',
  '320800000X': 'Community Based Residential Treatment Facility, Mental Illness',
  '320900000X': 'Community Based Residential Treatment Facility, Mental Retardation and/or Developmental Disabilities',
  '322D00000X': 'Residential Treatment Facility, Emotionally Disturbed Children',
  '323P00000X': 'Psychiatric Residential Treatment Facility',
  '324500000X': 'Substance Abuse Rehabilitation Facility',
  '331L00000X': 'Blood Bank',
  '332000000X': 'Military/U.S. Coast Guard Pharmacy',
  '332100000X': 'Department of Veterans Affairs (VA) Pharmacy',
  '332800000X': 'Indian Health Service/Tribal/Urban Indian Health (I/T/U) Pharmacy',
  '332900000X': 'Non-Pharmacy Dispensing Site',
  '332B00000X': 'Durable Medical Equipment & Medical Supplies',
  '332BC3200X': 'Customized Equipment',
  '332BD1200X': 'Dialysis Equipment & Supplies',
  '332BN1400X': 'Nursing Facility Supplies',
  '332BP3500X': 'Parenteral & Enteral Nutrition',
  '332BX2000X': 'Oxygen Equipment & Supplies',
  '333300000X': 'Hospital Pharmacy',
  '333600000X': 'Pharmacy',
  '3336C0002X': 'Clinic Pharmacy',
  '3336C0003X': 'Community/Retail Pharmacy',
  '3336C0004X': 'Compounding Pharmacy',
  '3336H0001X': 'Home Infusion Therapy Pharmacy',
  '3336I0012X': 'Institutional Pharmacy',
  '3336L0003X': 'Long Term Care Pharmacy',
  '3336M0002X': 'Mail Order Pharmacy',
  '3336M0003X': 'Managed Care Organization Pharmacy',
  '3336N0007X': 'Nuclear Pharmacy',
  '3336S0011X': 'Specialty Pharmacy',
} as const;

/**
 * Modifier Codes (Selected Common Modifiers)
 */
export const MODIFIER_CODES = {
  '22': 'Increased Procedural Services',
  '23': 'Unusual Anesthesia',
  '24': 'Unrelated E/M Service During Postoperative Period',
  '25': 'Significant, Separately Identifiable E/M Service',
  '26': 'Professional Component',
  '27': 'Multiple Outpatient Hospital E/M Encounters',
  '32': 'Mandated Services',
  '33': 'Preventive Services',
  '47': 'Anesthesia by Surgeon',
  '50': 'Bilateral Procedure',
  '51': 'Multiple Procedures',
  '52': 'Reduced Services',
  '53': 'Discontinued Procedure',
  '54': 'Surgical Care Only',
  '55': 'Postoperative Management Only',
  '56': 'Preoperative Management Only',
  '57': 'Decision for Surgery',
  '58': 'Staged or Related Procedure',
  '59': 'Distinct Procedural Service',
  '62': 'Two Surgeons',
  '63': 'Procedure on Infants Less Than 4 kg',
  '66': 'Surgical Team',
  '73': 'Discontinued Outpatient Procedure Prior to Anesthesia',
  '74': 'Discontinued Outpatient Procedure After Anesthesia',
  '76': 'Repeat Procedure by Same Physician',
  '77': 'Repeat Procedure by Another Physician',
  '78': 'Unplanned Return to OR',
  '79': 'Unrelated Procedure During Postoperative Period',
  '80': 'Assistant Surgeon',
  '81': 'Minimum Assistant Surgeon',
  '82': 'Assistant Surgeon When Qualified Resident Not Available',
  '90': 'Reference (Outside) Laboratory',
  '91': 'Repeat Clinical Lab Test',
  '92': 'Alternative Laboratory Platform Testing',
  '95': 'Synchronous Telemedicine Service',
  '96': 'Habilitative Services',
  '97': 'Rehabilitative Services',
  '99': 'Multiple Modifiers',
  AA: 'Anesthesia Services by Anesthesiologist',
  AD: 'Medical Supervision by Physician, More Than 4 Concurrent Procedures',
  AS: 'Physician Assistant, Nurse Practitioner, or CNS Services',
  CC: 'Procedure Code Change',
  CR: 'Catastrophe/Disaster Related',
  EP: 'Service Provided as Part of Medicaid EPSDT Program',
  ET: 'Emergency Services',
  EY: 'No Physician or Practitioner Ordered Service',
  GA: 'Waiver of Liability on File',
  GB: 'Claim Being Resubmitted for Payment',
  GC: 'Service Performed by Resident Under Teaching Physician',
  GE: 'Service Performed by Resident Without Teaching Physician',
  GG: 'Performance and Payment of a Screening Mammogram',
  GH: 'Diagnostic Mammogram Converted from Screening Mammogram',
  GJ: 'Opt Out Physician or Practitioner Emergency/Urgent Service',
  GK: 'Reasonable and Necessary Item/Service for Patient',
  GL: 'Medically Unnecessary Upgrade Provided, Billed as Upgrade',
  GN: 'Services Delivered Under Outpatient Speech Language Pathology',
  GO: 'Services Delivered Under Outpatient Occupational Therapy',
  GP: 'Services Delivered Under Outpatient Physical Therapy',
  GQ: 'Via Asynchronous Telecommunications System',
  GT: 'Via Interactive Audio and Video Telecommunication Systems',
  GV: 'Attending Physician Not Employed by Patient\'s Hospice',
  GW: 'Service Not Related to Hospice Patient\'s Terminal Condition',
  GX: 'Notice of Liability - Voluntary Under Payer Policy',
  GY: 'Item or Service Statutorily Excluded',
  GZ: 'Item or Service Expected to Be Denied as Not Reasonable',
  JW: 'Drug Amount Discarded/Not Administered',
  KX: 'Requirements Specified in Medical Policy Have Been Met',
  LT: 'Left Side',
  RT: 'Right Side',
  Q5: 'Service Furnished by Substitute Physician Under Reciprocal Billing',
  Q6: 'Service Furnished by Locum Tenens Physician',
  QJ: 'Services Provided to Prisoner in State/Local Custody',
  QK: 'Medical Direction of 2, 3, or 4 Concurrent Anesthesia Procedures',
  QS: 'Monitored Anesthesia Care Service',
  QW: 'CLIA Waived Test',
  QX: 'CRNA Service With Medical Direction by Physician',
  QY: 'Medical Direction of One CRNA by Anesthesiologist',
  QZ: 'CRNA Service Without Medical Direction by Physician',
  SG: 'Ambulatory Surgical Center (ASC) Facility Service',
  TC: 'Technical Component',
  XE: 'Separate Encounter',
  XP: 'Separate Practitioner',
  XS: 'Separate Structure',
  XU: 'Unusual Non-Overlapping Service',
} as const;

export type PlaceOfServiceCode = keyof typeof PLACE_OF_SERVICE_CODES;
export type TypeOfBillCode = keyof typeof TYPE_OF_BILL_CODES;
export type RevenueCode = keyof typeof REVENUE_CODES;
export type TaxonomyCode = keyof typeof TAXONOMY_CODES;
export type ModifierCode = keyof typeof MODIFIER_CODES;
